# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107iKI_Yj7_YfEwrLaBvdCKJp8mz_qYJc
"""

# Autor: Jonáš Kracík
# email: Kraci75477@mot.sps-dopravni.cz
# Téma: Hra Bulls and Cows

import random

# --- PŘÍPRAVA HRY ---

# Vytvoření seznamu číslic a vygenerování náhodného čísla
cislice = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
random.shuffle(cislice)

# Musíme zajistit, aby na začátku nebyla nula
if cislice[0] == "0":
    tajne_cislo_list = cislice[1:5]
else:
    tajne_cislo_list = cislice[0:4]

# Převedeme seznam na textový řetězec, aby se nám s ním lépe pracovalo
tajne_cislo = "".join(tajne_cislo_list)

print("Vítejte u hry Bulls and Cows!")
print("-" * 40)
print("Myslím si unikátní čtyřmístné číslo.")
print("-" * 40)

pocet_pokusu = 0

# --- HLAVNÍ SMYČKA ---

while True:
    hadane_cislo = input("Zadej svůj tip: ")

    # 1. Kontrola chyb ve vstupu
    if not hadane_cislo.isdigit():
        print("Chyba: Musíš zadat jen číslice!")
        continue

    if len(hadane_cislo) != 4:
        print("Chyba: Číslo musí mít přesně 4 cifry!")
        continue

    if hadane_cislo[0] == "0":
        print("Chyba: Číslo nesmí začínat nulou!")
        continue

    # Kontrola unikátnosti číslic (pomocí setu - to se v IT učí)
    if len(set(hadane_cislo)) != 4:
        print("Chyba: Všechny číslice musí být unikátní!")
        continue

    pocet_pokusu += 1

    # 2. Kontrola výhry
    if hadane_cislo == tajne_cislo:
        print(f"Gratuluji! Uhodl jsi to na {pocet_pokusu}. pokus.")

        # Hodnocení podle počtu pokusů
        if pocet_pokusu <= 10:
            print("To je vynikající výsledek!")
        elif pocet_pokusu <= 20:
            print("To je slušný průměr.")
        else:
            print("Dost ses zapotil, ale máš to.")
        break

    # 3. Výpočet Bulls a Cows (klasickým cyklem)
    bulls = 0
    cows = 0

    for i in range(4):
        if hadane_cislo[i] == tajne_cislo[i]:
            bulls += 1
        elif hadane_cislo[i] in tajne_cislo:
            cows += 1

    # 4. Výpis výsledku kola
    # Ošetření jednotného čísla (bull vs bulls)
    slovo_bull = "bull" if bulls == 1 else "bulls"
    slovo_cow = "cow" if cows == 1 else "cows"

    print(f"Výsledek: {bulls} {slovo_bull}, {cows} {slovo_cow}")
    print("-" * 40)